name: MongoConfigs
version: "${project.version}"
main: xyz.wtje.mongoconfigs.paper.MongoConfigsPlugin
api-version: "1.20"
author: aiikk
website: https://github.com/aiikk/mongo-configs
description: Advanced MongoDB configuration and translation management library



permissions:
  mongoconfigs.admin:
    description: Access to admin commands
    default: op
    children:
      mongoconfigs.hotreload: true
  mongoconfigs.language:
    description: Access to language selection
    default: true
  mongoconfigs.reload:
    description: Access to reload commands
    default: op
  mongoconfigs.hotreload:
    description: Access to hot-reload commands
    default: op

commands:
  language:
    description: Select your language
    usage: /<command> [language]
    permission: mongoconfigs.language
    aliases: [lang, jezyk]
  mongoconfigs:
    description: MongoDB Configs management
    usage: /<command> <subcommand>
    permission: mongoconfigs.admin
    aliases: [mconfig, mc]
  configsmanager:
    description: Configuration cache management
    usage: /<command> <reload|stats|collections|create|info>
    permission: mongoconfigs.admin
    aliases: [cfgmgr, cm]
  hotreload:
    description: Hot-reload management commands
    usage: /<command> [gui|cache|all|status]
    permission: mongoconfigs.hotreload
    aliases: [hr]
