name: Sync wiki from .github/wiki

on:
  push:
    paths:
      - ".github/wiki/**"
  workflow_dispatch:

# kluczowe: zezwól na zapis, inaczej będzie 403
permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      # Klonujemy *wiki* jako osobne repo do folderu wiki-repo
      # to od razu da Ci właściwy branch `master` dla wiki
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          # domyślny GITHUB_TOKEN wystarczy dla tego samego repo;
          # gdybyś pchał do innego repo/wiki, podmień na PAT:
          # token: ${{ secrets.WIKI_TOKEN }}

      - name: Sync files into wiki working tree
        run: |
          rsync -av --delete --exclude '.git/' .github/wiki/ wiki-repo/

      - name: Commit & push (to wiki/master)
        working-directory: wiki-repo
        shell: bash
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if ! git diff --quiet || ! git diff --cached --quiet; then
            git add -A
            git commit -m "Sync wiki from $GITHUB_SHA"
            # wiki używa 'master' — pchamy aktualną HEAD na master
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
